### ISSUE TITLE
This is SO COOL

### ISSUE THREAD

**Issue by heynemann** [theatlantic/thumbor-video-engine#1]
Thumbor creator here! Just wanted to say this is SO cool! Thanks for contributing this back to the community!
Hope thumbor is helping The Atlantic as much as it does the other companies that use it!

**Comment by fdintino** [comment]
Thanks for the kind note!

Would it be helpful if I opened a pull request adding this package to the "plugins" section of the thumbor docs?

**Comment by heynemann** [comment]
Definitely!!! Closing this not to polute your issues. Thanks again!
