### ISSUE TITLE
Thumbor 7 Upgrade

### ISSUE THREAD

**Issue by heynemann** [theatlantic/thumbor-video-engine#10]
Hey incredible work here! What do you say we upgrade to thumbor 7? I'm here to support on any doubts you may have regarding the transition!

Great job again and I'm adding this to awesome thumbor :) Hopefully we'll see this migrated to python 3 and thumbor 7!

**Comment by fdintino** [comment]
It's actually already compatible with both thumbor 6 and thumbor 7! (and has been for a while). I made the thumbor versions clearer in the github actions CI build, and added more python 3 versions to the test matrix. See [the latest run on the master branch](https://github.com/theatlantic/thumbor-video-engine/actions/runs/1747213004).

**Comment by mpdude** [comment]
So we can close this :-)?

Maybe add a remark in the README file that it works for both versions.
