### ISSUE TITLE
Video engine `format` filter blocks newer image formats in Thumbor

### ISSUE THREAD

**Issue by mpdude** [theatlantic/thumbor-video-engine#23]
Hey there,

in my configuration file, I specify the following:

```
 FILTERS = [
     'thumbor.filters.quality',
     'thumbor_video_engine.filters.format',
     'thumbor.filters.blur',
     ...
```

So, I am using `thumbor_video_engine.filters.format` only and not adding `thumbor.filters.format`.

Now I noticed that support for newer image formats like AVIF, which have been added by e. g. in https://github.com/thumbor/thumbor/pull/1476, do not work. They are rejected by the filter with a `Format not allowed` log message.

So, my question is:

Should it be possible to use the newer image formats by adding both filter class names to the `FILTER` setting, or would that not work since the filters (the `format` name, maybe?) would be mutually exclusive?

Is there a way to make this video engine add a few formats without having to re-define or override the other formats? I mean, if we need to amend the list of supported formats here in this repo, how can we make sure we don't have to come back in two years time and add yet another format?

**Comment by mpdude** [comment]
Note to future me: Once I get this working, review the Thumbor `'thumbor.result_storages.file_storage'` result storage. It does some special case handling for auto webp detections, and it might be missing support for other formats as well. Might not be an issue though if no auto-detection is used and filters are part of the URL, so they end up in the cache key.

**Comment by mpdude** [comment]
@fdintino maybe you could give starting pointers what a potential fix might look like?

**Comment by mpdude** [comment]
@fdintino maybe you could give starting pointers what a potential fix might look like?

**Comment by fdintino** [comment]
Sorry for the delay in responding, I've been out on paternity leave. We (at the Atlantic) have a layer built on top of thumbor-video-engine that supports AVIF and also has the appropriate result storage handling for auto-avif (our auto-AVIF implementation predates the one in thumbor core) so it's definitely doable. I'll try to find some time to take a closer look at this soon.

**Comment by mpdude** [comment]
That’s great news. Enjoy!

**Comment by mpdude** [comment]
Finally I found the time to give the new version a try... 🎉 Works like a charm!

Thank you very much @fdintino
